apiVersion: batch/v1
kind: Job
metadata:
  name: cmdb-collector
  namespace: monitoring
spec:
  completions: 1     			# 需要运行的pod数量
  parallelism: 1      			# 允许并发运行的pod数量
  activeDeadlineSeconds: 360  	# pod运行的超时时间
  template:
    metadata:
      labels:
        app: cmdb-collector
        release: cmdb-collector
    spec:
      containers:
        - name: cmdb-collector
          image: registry-jinan-lab.inspurcloud.cn/service/lma/cmdb-collector:1.0.0
          imagePullPolicy: Always
      restartPolicy: Never
      serviceAccount: cmdb-collector
      serviceAccountName: cmdb-collector
