apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmdb-collector
  namespace: monitoring

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmdb-collector
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - namespaces
      - nodes
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - events
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch




---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmdb-collector
subjects:
  - kind: ServiceAccount
    name: cmdb-collector
    namespace: monitoring
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cmdb-collector
  apiGroup: ""
