apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmdb-collector
  namespace: monitoring

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmdb-collector
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmdb-collector
subjects:
  - kind: ServiceAccount
    name: cmdb-collector
    namespace: monitoring
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cmdb-collector
  apiGroup: ""
